# Generated by Django 6.1.1 on 2026-10-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('parser_source', models.CharField(choices=[('requests_bs4', 'Requests / BS4'), ('selenium', 'Selenium'), ('playwright', 'Playwright')], default='requests_bs4', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
