# Generated by Django 6.1.1 on 2026-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parser_source',
            field=models.CharField(choices=[('requests_bs4', 'Requests / BS4'), ('selenium', 'Selenium'), ('playwright', 'Playwright')], default='requests_bs4', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_code', 'parser_source')},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
