# Generated by Django 6.1.1 on 2026-10-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_product_parser_source_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
