# Generated by Django 6.1.1 on 2026-10-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_product_reviews_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
